server:
  port: 9988
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 300
    min-spare-threads: 30
# 日志配置
logging:
  level:
    com.think: info
    org.springframework: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wq3o7OU5Twt59JNj
    url: jdbc:mysql://localhost:3306/train_data?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  devtools:
    restart:
      # 热部署开关
      enabled: true
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.think.**.entity
  global-config:
    #数据库相关配置
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
